name: DNSControl

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/dnscontrol.yml"
      - "dnsconfig.js"
      - "utils/reserved.json"
      - "utils/internal.json"

  pull_request:
    paths:
      - "dnsconfig.js"
      - "utils/reserved.json"
      - "utils/internal.json"

  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-dnscontrol
  cancel-in-progress: true

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: gacts/install-dnscontrol@107ad2b0e96e9973ae69cba13228d4e819d602a6 # v1.3.4
        with:
          version: 4.14.0

      - name: Run DNSControl checks
        run: dnscontrol check
