name: Publish

on:
  push:
    branches: [main]
    paths:
      - "domains/*"
      - "domains/**"
      - ".github/workflows/publish.yml"
      - "utils/reserved.json"
      - "dnsconfig.js"

  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-publish
  cancel-in-progress: false

jobs:
  dns:
    name: DNS
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: gacts/install-dnscontrol@107ad2b0e96e9973ae69cba13228d4e819d602a6 # v1.3.4
        with:
          version: 4.14.0

      - name: Generate creds.json
        run: echo '{"cloudflare":{"TYPE":"CLOUDFLAREAPI","apitoken":"$CLOUDFLARE_API_TOKEN"}}' > ./creds.json

      - name: Push DNS records
        run: dnscontrol push
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  index:
    name: Index
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ secrets.BOT || github.token }}
          ref: ${{ github.ref }}

      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: 20.x

      - name: Rebuild domains.json
        run: node utils/build-index.js

      - name: Commit domains.json
        run: |
          if [ -z "$(git status --porcelain domains.json)" ]; then
            echo "domains.json is already up to date."
            exit 0
          fi

          git config user.name "has-a-link-bot"
          git config user.email "bot@has-a.link"
          git add domains.json
          git commit -m "chore: rebuild domains.json [skip ci]"
          git push
